services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jira-clone-server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: jira-clone-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: jira_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
